-- Create continents table
CREATE TABLE IF NOT EXISTS continents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    order_index INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert continents
INSERT INTO continents (name, order_index) VALUES
    ('Europe', 1),
    ('Asia', 2),
    ('North America', 3),
    ('South America', 4),
    ('Africa', 5),
    ('Oceania', 6),
    ('Antarctica', 7)
ON CONFLICT (name) DO NOTHING;

-- Add columns to countries
ALTER TABLE countries ADD COLUMN IF NOT EXISTS continent_id UUID REFERENCES continents(id);
ALTER TABLE countries ADD COLUMN IF NOT EXISTS flag_emoji TEXT;

-- Clear existing countries
DELETE FROM countries;

-- EUROPE (44 countries)
INSERT INTO countries (name, code, flag_emoji, continent_id) VALUES
    ('Albania', 'AL', '🇦🇱', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Andorra', 'AD', '🇦🇩', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Austria', 'AT', '🇦🇹', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Belarus', 'BY', '🇧🇾', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Belgium', 'BE', '🇧🇪', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Bosnia and Herzegovina', 'BA', '🇧🇦', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Bulgaria', 'BG', '🇧🇬', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Croatia', 'HR', '🇭🇷', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Cyprus', 'CY', '🇨🇾', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Czech Republic', 'CZ', '🇨🇿', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Denmark', 'DK', '🇩🇰', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Estonia', 'EE', '🇪🇪', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Finland', 'FI', '🇫🇮', (SELECT id FROM continents WHERE name = 'Europe')),
    ('France', 'FR', '🇫🇷', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Germany', 'DE', '🇩🇪', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Greece', 'GR', '🇬🇷', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Hungary', 'HU', '🇭🇺', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Iceland', 'IS', '🇮🇸', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Ireland', 'IE', '🇮🇪', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Italy', 'IT', '🇮🇹', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Kosovo', 'XK', '🇽🇰', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Latvia', 'LV', '🇱🇻', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Liechtenstein', 'LI', '🇱🇮', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Lithuania', 'LT', '🇱🇹', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Luxembourg', 'LU', '🇱🇺', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Malta', 'MT', '🇲🇹', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Moldova', 'MD', '🇲🇩', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Monaco', 'MC', '🇲🇨', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Montenegro', 'ME', '🇲🇪', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Netherlands', 'NL', '🇳🇱', (SELECT id FROM continents WHERE name = 'Europe')),
    ('North Macedonia', 'MK', '🇲🇰', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Norway', 'NO', '🇳🇴', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Poland', 'PL', '🇵🇱', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Portugal', 'PT', '🇵🇹', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Romania', 'RO', '🇷🇴', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Russia', 'RU', '🇷🇺', (SELECT id FROM continents WHERE name = 'Europe')),
    ('San Marino', 'SM', '🇸🇲', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Serbia', 'RS', '🇷🇸', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Slovakia', 'SK', '🇸🇰', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Slovenia', 'SI', '🇸🇮', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Spain', 'ES', '🇪🇸', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Sweden', 'SE', '🇸🇪', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Switzerland', 'CH', '🇨🇭', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Ukraine', 'UA', '🇺🇦', (SELECT id FROM continents WHERE name = 'Europe')),
    ('United Kingdom', 'GB', '🇬🇧', (SELECT id FROM continents WHERE name = 'Europe')),
    ('Vatican City', 'VA', '🇻🇦', (SELECT id FROM continents WHERE name = 'Europe'));

-- ASIA (50 countries)
INSERT INTO countries (name, code, flag_emoji, continent_id) VALUES
    ('Afghanistan', 'AF', '🇦🇫', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Armenia', 'AM', '🇦🇲', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Azerbaijan', 'AZ', '🇦🇿', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Bahrain', 'BH', '🇧🇭', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Bangladesh', 'BD', '🇧🇩', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Bhutan', 'BT', '🇧🇹', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Brunei', 'BN', '🇧🇳', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Cambodia', 'KH', '🇰🇭', (SELECT id FROM continents WHERE name = 'Asia')),
    ('China', 'CN', '🇨🇳', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Georgia', 'GE', '🇬🇪', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Hong Kong', 'HK', '🇭🇰', (SELECT id FROM continents WHERE name = 'Asia')),
    ('India', 'IN', '🇮🇳', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Indonesia', 'ID', '🇮🇩', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Iran', 'IR', '🇮🇷', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Iraq', 'IQ', '🇮🇶', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Israel', 'IL', '🇮🇱', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Japan', 'JP', '🇯🇵', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Jordan', 'JO', '🇯🇴', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Kazakhstan', 'KZ', '🇰🇿', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Kuwait', 'KW', '🇰🇼', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Kyrgyzstan', 'KG', '🇰🇬', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Laos', 'LA', '🇱🇦', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Lebanon', 'LB', '🇱🇧', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Macau', 'MO', '🇲🇴', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Malaysia', 'MY', '🇲🇾', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Maldives', 'MV', '🇲🇻', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Mongolia', 'MN', '🇲🇳', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Myanmar', 'MM', '🇲🇲', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Nepal', 'NP', '🇳🇵', (SELECT id FROM continents WHERE name = 'Asia')),
    ('North Korea', 'KP', '🇰🇵', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Oman', 'OM', '🇴🇲', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Pakistan', 'PK', '🇵🇰', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Palestine', 'PS', '🇵🇸', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Philippines', 'PH', '🇵🇭', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Qatar', 'QA', '🇶🇦', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Saudi Arabia', 'SA', '🇸🇦', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Singapore', 'SG', '🇸🇬', (SELECT id FROM continents WHERE name = 'Asia')),
    ('South Korea', 'KR', '🇰🇷', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Sri Lanka', 'LK', '🇱🇰', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Syria', 'SY', '🇸🇾', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Taiwan', 'TW', '🇹🇼', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Tajikistan', 'TJ', '🇹🇯', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Thailand', 'TH', '🇹🇭', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Timor-Leste', 'TL', '🇹🇱', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Turkey', 'TR', '🇹🇷', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Turkmenistan', 'TM', '🇹🇲', (SELECT id FROM continents WHERE name = 'Asia')),
    ('United Arab Emirates', 'AE', '🇦🇪', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Uzbekistan', 'UZ', '🇺🇿', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Vietnam', 'VN', '🇻🇳', (SELECT id FROM continents WHERE name = 'Asia')),
    ('Yemen', 'YE', '🇾🇪', (SELECT id FROM continents WHERE name = 'Asia'));

-- NORTH AMERICA (23 countries)
INSERT INTO countries (name, code, flag_emoji, continent_id) VALUES
    ('Antigua and Barbuda', 'AG', '🇦🇬', (SELECT id FROM continents WHERE name = 'North America')),
    ('Bahamas', 'BS', '🇧🇸', (SELECT id FROM continents WHERE name = 'North America')),
    ('Barbados', 'BB', '🇧🇧', (SELECT id FROM continents WHERE name = 'North America')),
    ('Belize', 'BZ', '🇧🇿', (SELECT id FROM continents WHERE name = 'North America')),
    ('Canada', 'CA', '🇨🇦', (SELECT id FROM continents WHERE name = 'North America')),
    ('Costa Rica', 'CR', '🇨🇷', (SELECT id FROM continents WHERE name = 'North America')),
    ('Cuba', 'CU', '🇨🇺', (SELECT id FROM continents WHERE name = 'North America')),
    ('Dominica', 'DM', '🇩🇲', (SELECT id FROM continents WHERE name = 'North America')),
    ('Dominican Republic', 'DO', '🇩🇴', (SELECT id FROM continents WHERE name = 'North America')),
    ('El Salvador', 'SV', '🇸🇻', (SELECT id FROM continents WHERE name = 'North America')),
    ('Grenada', 'GD', '🇬🇩', (SELECT id FROM continents WHERE name = 'North America')),
    ('Guatemala', 'GT', '🇬🇹', (SELECT id FROM continents WHERE name = 'North America')),
    ('Haiti', 'HT', '🇭🇹', (SELECT id FROM continents WHERE name = 'North America')),
    ('Honduras', 'HN', '🇭🇳', (SELECT id FROM continents WHERE name = 'North America')),
    ('Jamaica', 'JM', '🇯🇲', (SELECT id FROM continents WHERE name = 'North America')),
    ('Mexico', 'MX', '🇲🇽', (SELECT id FROM continents WHERE name = 'North America')),
    ('Nicaragua', 'NI', '🇳🇮', (SELECT id FROM continents WHERE name = 'North America')),
    ('Panama', 'PA', '🇵🇦', (SELECT id FROM continents WHERE name = 'North America')),
    ('Puerto Rico', 'PR', '🇵🇷', (SELECT id FROM continents WHERE name = 'North America')),
    ('Saint Kitts and Nevis', 'KN', '🇰🇳', (SELECT id FROM continents WHERE name = 'North America')),
    ('Saint Lucia', 'LC', '🇱🇨', (SELECT id FROM continents WHERE name = 'North America')),
    ('Saint Vincent and the Grenadines', 'VC', '🇻🇨', (SELECT id FROM continents WHERE name = 'North America')),
    ('Trinidad and Tobago', 'TT', '🇹🇹', (SELECT id FROM continents WHERE name = 'North America')),
    ('United States', 'US', '🇺🇸', (SELECT id FROM continents WHERE name = 'North America'));

-- SOUTH AMERICA (12 countries)
INSERT INTO countries (name, code, flag_emoji, continent_id) VALUES
    ('Argentina', 'AR', '🇦🇷', (SELECT id FROM continents WHERE name = 'South America')),
    ('Bolivia', 'BO', '🇧🇴', (SELECT id FROM continents WHERE name = 'South America')),
    ('Brazil', 'BR', '🇧🇷', (SELECT id FROM continents WHERE name = 'South America')),
    ('Chile', 'CL', '🇨🇱', (SELECT id FROM continents WHERE name = 'South America')),
    ('Colombia', 'CO', '🇨🇴', (SELECT id FROM continents WHERE name = 'South America')),
    ('Ecuador', 'EC', '🇪🇨', (SELECT id FROM continents WHERE name = 'South America')),
    ('Guyana', 'GY', '🇬🇾', (SELECT id FROM continents WHERE name = 'South America')),
    ('Paraguay', 'PY', '🇵🇾', (SELECT id FROM continents WHERE name = 'South America')),
    ('Peru', 'PE', '🇵🇪', (SELECT id FROM continents WHERE name = 'South America')),
    ('Suriname', 'SR', '🇸🇷', (SELECT id FROM continents WHERE name = 'South America')),
    ('Uruguay', 'UY', '🇺🇾', (SELECT id FROM continents WHERE name = 'South America')),
    ('Venezuela', 'VE', '🇻🇪', (SELECT id FROM continents WHERE name = 'South America'));

-- AFRICA (54 countries)
INSERT INTO countries (name, code, flag_emoji, continent_id) VALUES
    ('Algeria', 'DZ', '🇩🇿', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Angola', 'AO', '🇦🇴', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Benin', 'BJ', '🇧🇯', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Botswana', 'BW', '🇧🇼', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Burkina Faso', 'BF', '🇧🇫', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Burundi', 'BI', '🇧🇮', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Cameroon', 'CM', '🇨🇲', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Cape Verde', 'CV', '🇨🇻', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Central African Republic', 'CF', '🇨🇫', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Chad', 'TD', '🇹🇩', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Comoros', 'KM', '🇰🇲', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Congo', 'CG', '🇨🇬', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Democratic Republic of the Congo', 'CD', '🇨🇩', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Djibouti', 'DJ', '🇩🇯', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Egypt', 'EG', '🇪🇬', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Equatorial Guinea', 'GQ', '🇬🇶', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Eritrea', 'ER', '🇪🇷', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Eswatini', 'SZ', '🇸🇿', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Ethiopia', 'ET', '🇪🇹', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Gabon', 'GA', '🇬🇦', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Gambia', 'GM', '🇬🇲', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Ghana', 'GH', '🇬🇭', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Guinea', 'GN', '🇬🇳', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Guinea-Bissau', 'GW', '🇬🇼', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Ivory Coast', 'CI', '🇨🇮', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Kenya', 'KE', '🇰🇪', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Lesotho', 'LS', '🇱🇸', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Liberia', 'LR', '🇱🇷', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Libya', 'LY', '🇱🇾', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Madagascar', 'MG', '🇲🇬', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Malawi', 'MW', '🇲🇼', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Mali', 'ML', '🇲🇱', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Mauritania', 'MR', '🇲🇷', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Mauritius', 'MU', '🇲🇺', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Morocco', 'MA', '🇲🇦', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Mozambique', 'MZ', '🇲🇿', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Namibia', 'NA', '🇳🇦', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Niger', 'NE', '🇳🇪', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Nigeria', 'NG', '🇳🇬', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Rwanda', 'RW', '🇷🇼', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Sao Tome and Principe', 'ST', '🇸🇹', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Senegal', 'SN', '🇸🇳', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Seychelles', 'SC', '🇸🇨', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Sierra Leone', 'SL', '🇸🇱', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Somalia', 'SO', '🇸🇴', (SELECT id FROM continents WHERE name = 'Africa')),
    ('South Africa', 'ZA', '🇿🇦', (SELECT id FROM continents WHERE name = 'Africa')),
    ('South Sudan', 'SS', '🇸🇸', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Sudan', 'SD', '🇸🇩', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Tanzania', 'TZ', '🇹🇿', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Togo', 'TG', '🇹🇬', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Tunisia', 'TN', '🇹🇳', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Uganda', 'UG', '🇺🇬', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Zambia', 'ZM', '🇿🇲', (SELECT id FROM continents WHERE name = 'Africa')),
    ('Zimbabwe', 'ZW', '🇿🇼', (SELECT id FROM continents WHERE name = 'Africa'));

-- OCEANIA (14 countries)
INSERT INTO countries (name, code, flag_emoji, continent_id) VALUES
    ('Australia', 'AU', '🇦🇺', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Fiji', 'FJ', '🇫🇯', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('French Polynesia', 'PF', '🇵🇫', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Guam', 'GU', '🇬🇺', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Kiribati', 'KI', '🇰🇮', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Marshall Islands', 'MH', '🇲🇭', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Micronesia', 'FM', '🇫🇲', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Nauru', 'NR', '🇳🇷', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('New Caledonia', 'NC', '🇳🇨', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('New Zealand', 'NZ', '🇳🇿', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Palau', 'PW', '🇵🇼', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Papua New Guinea', 'PG', '🇵🇬', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Samoa', 'WS', '🇼🇸', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Solomon Islands', 'SB', '🇸🇧', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Tonga', 'TO', '🇹🇴', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Tuvalu', 'TV', '🇹🇻', (SELECT id FROM continents WHERE name = 'Oceania')),
    ('Vanuatu', 'VU', '🇻🇺', (SELECT id FROM continents WHERE name = 'Oceania'));

-- ANTARCTICA (for completeness)
INSERT INTO countries (name, code, flag_emoji, continent_id) VALUES
    ('Antarctica', 'AQ', '🇦🇶', (SELECT id FROM continents WHERE name = 'Antarctica'));
