-- Add comprehensive list of world countries
INSERT INTO countries (code, name, emoji, continent) VALUES
-- Europe
('AL', 'Albania', '🇦🇱', 'Europe'),
('AD', 'Andorra', '🇦🇩', 'Europe'),
('AM', 'Armenia', '🇦🇲', 'Europe'),
('BY', 'Belarus', '🇧🇾', 'Europe'),
('BE', 'Belgium', '🇧🇪', 'Europe'),
('BA', 'Bosnia and Herzegovina', '🇧🇦', 'Europe'),
('BG', 'Bulgaria', '🇧🇬', 'Europe'),
('CY', 'Cyprus', '🇨🇾', 'Europe'),
('DK', 'Denmark', '🇩🇰', 'Europe'),
('EE', 'Estonia', '🇪🇪', 'Europe'),
('FI', 'Finland', '🇫🇮', 'Europe'),
('GE', 'Georgia', '🇬🇪', 'Europe'),
('HU', 'Hungary', '🇭🇺', 'Europe'),
('IS', 'Iceland', '🇮🇸', 'Europe'),
('IE', 'Ireland', '🇮🇪', 'Europe'),
('LV', 'Latvia', '🇱🇻', 'Europe'),
('LI', 'Liechtenstein', '🇱🇮', 'Europe'),
('LT', 'Lithuania', '🇱🇹', 'Europe'),
('LU', 'Luxembourg', '🇱🇺', 'Europe'),
('MT', 'Malta', '🇲🇹', 'Europe'),
('MD', 'Moldova', '🇲🇩', 'Europe'),
('MC', 'Monaco', '🇲🇨', 'Europe'),
('ME', 'Montenegro', '🇲🇪', 'Europe'),
('MK', 'North Macedonia', '🇲🇰', 'Europe'),
('NO', 'Norway', '🇳🇴', 'Europe'),
('PL', 'Poland', '🇵🇱', 'Europe'),
('RO', 'Romania', '🇷🇴', 'Europe'),
('RU', 'Russia', '🇷🇺', 'Europe'),
('SM', 'San Marino', '🇸🇲', 'Europe'),
('RS', 'Serbia', '🇷🇸', 'Europe'),
('SK', 'Slovakia', '🇸🇰', 'Europe'),
('SI', 'Slovenia', '🇸🇮', 'Europe'),
('SE', 'Sweden', '🇸🇪', 'Europe'),
('UA', 'Ukraine', '🇺🇦', 'Europe'),
('VA', 'Vatican City', '🇻🇦', 'Europe'),
-- Asia
('AF', 'Afghanistan', '🇦🇫', 'Asia'),
('AZ', 'Azerbaijan', '🇦🇿', 'Asia'),
('BH', 'Bahrain', '🇧🇭', 'Asia'),
('BD', 'Bangladesh', '🇧🇩', 'Asia'),
('BT', 'Bhutan', '🇧🇹', 'Asia'),
('BN', 'Brunei', '🇧🇳', 'Asia'),
('KH', 'Cambodia', '🇰🇭', 'Asia'),
('HK', 'Hong Kong', '🇭🇰', 'Asia'),
('IR', 'Iran', '🇮🇷', 'Asia'),
('IQ', 'Iraq', '🇮🇶', 'Asia'),
('IL', 'Israel', '🇮🇱', 'Asia'),
('JO', 'Jordan', '🇯🇴', 'Asia'),
('KZ', 'Kazakhstan', '🇰🇿', 'Asia'),
('KW', 'Kuwait', '🇰🇼', 'Asia'),
('KG', 'Kyrgyzstan', '🇰🇬', 'Asia'),
('LA', 'Laos', '🇱🇦', 'Asia'),
('LB', 'Lebanon', '🇱🇧', 'Asia'),
('MO', 'Macau', '🇲🇴', 'Asia'),
('MY', 'Malaysia', '🇲🇾', 'Asia'),
('MV', 'Maldives', '🇲🇻', 'Asia'),
('MN', 'Mongolia', '🇲🇳', 'Asia'),
('MM', 'Myanmar', '🇲🇲', 'Asia'),
('NP', 'Nepal', '🇳🇵', 'Asia'),
('KP', 'North Korea', '🇰🇵', 'Asia'),
('OM', 'Oman', '🇴🇲', 'Asia'),
('PK', 'Pakistan', '🇵🇰', 'Asia'),
('PS', 'Palestine', '🇵🇸', 'Asia'),
('PH', 'Philippines', '🇵🇭', 'Asia'),
('QA', 'Qatar', '🇶🇦', 'Asia'),
('SA', 'Saudi Arabia', '🇸🇦', 'Asia'),
('SG', 'Singapore', '🇸🇬', 'Asia'),
('KR', 'South Korea', '🇰🇷', 'Asia'),
('LK', 'Sri Lanka', '🇱🇰', 'Asia'),
('SY', 'Syria', '🇸🇾', 'Asia'),
('TW', 'Taiwan', '🇹🇼', 'Asia'),
('TJ', 'Tajikistan', '🇹🇯', 'Asia'),
('TM', 'Turkmenistan', '🇹🇲', 'Asia'),
('AE', 'United Arab Emirates', '🇦🇪', 'Asia'),
('UZ', 'Uzbekistan', '🇺🇿', 'Asia'),
('YE', 'Yemen', '🇾🇪', 'Asia'),
-- Africa
('DZ', 'Algeria', '🇩🇿', 'Africa'),
('AO', 'Angola', '🇦🇴', 'Africa'),
('BJ', 'Benin', '🇧🇯', 'Africa'),
('BW', 'Botswana', '🇧🇼', 'Africa'),
('BF', 'Burkina Faso', '🇧🇫', 'Africa'),
('BI', 'Burundi', '🇧🇮', 'Africa'),
('CV', 'Cape Verde', '🇨🇻', 'Africa'),
('CM', 'Cameroon', '🇨🇲', 'Africa'),
('CF', 'Central African Republic', '🇨🇫', 'Africa'),
('TD', 'Chad', '🇹🇩', 'Africa'),
('KM', 'Comoros', '🇰🇲', 'Africa'),
('CD', 'Democratic Republic of the Congo', '🇨🇩', 'Africa'),
('CG', 'Republic of the Congo', '🇨🇬', 'Africa'),
('DJ', 'Djibouti', '🇩🇯', 'Africa'),
('ER', 'Eritrea', '🇪🇷', 'Africa'),
('SZ', 'Eswatini', '🇸🇿', 'Africa'),
('ET', 'Ethiopia', '🇪🇹', 'Africa'),
('GA', 'Gabon', '🇬🇦', 'Africa'),
('GM', 'Gambia', '🇬🇲', 'Africa'),
('GH', 'Ghana', '🇬🇭', 'Africa'),
('GN', 'Guinea', '🇬🇳', 'Africa'),
('GW', 'Guinea-Bissau', '🇬🇼', 'Africa'),
('CI', 'Ivory Coast', '🇨🇮', 'Africa'),
('LS', 'Lesotho', '🇱🇸', 'Africa'),
('LR', 'Liberia', '🇱🇷', 'Africa'),
('LY', 'Libya', '🇱🇾', 'Africa'),
('MG', 'Madagascar', '🇲🇬', 'Africa'),
('MW', 'Malawi', '🇲🇼', 'Africa'),
('ML', 'Mali', '🇲🇱', 'Africa'),
('MR', 'Mauritania', '🇲🇷', 'Africa'),
('MU', 'Mauritius', '🇲🇺', 'Africa'),
('MZ', 'Mozambique', '🇲🇿', 'Africa'),
('NA', 'Namibia', '🇳🇦', 'Africa'),
('NE', 'Niger', '🇳🇪', 'Africa'),
('NG', 'Nigeria', '🇳🇬', 'Africa'),
('RW', 'Rwanda', '🇷🇼', 'Africa'),
('ST', 'São Tomé and Príncipe', '🇸🇹', 'Africa'),
('SN', 'Senegal', '🇸🇳', 'Africa'),
('SC', 'Seychelles', '🇸🇨', 'Africa'),
('SL', 'Sierra Leone', '🇸🇱', 'Africa'),
('SO', 'Somalia', '🇸🇴', 'Africa'),
('SS', 'South Sudan', '🇸🇸', 'Africa'),
('SD', 'Sudan', '🇸🇩', 'Africa'),
('TZ', 'Tanzania', '🇹🇿', 'Africa'),
('TG', 'Togo', '🇹🇬', 'Africa'),
('TN', 'Tunisia', '🇹🇳', 'Africa'),
('UG', 'Uganda', '🇺🇬', 'Africa'),
('ZM', 'Zambia', '🇿🇲', 'Africa'),
('ZW', 'Zimbabwe', '🇿🇼', 'Africa'),
-- North America
('AG', 'Antigua and Barbuda', '🇦🇬', 'North America'),
('BS', 'Bahamas', '🇧🇸', 'North America'),
('BB', 'Barbados', '🇧🇧', 'North America'),
('BZ', 'Belize', '🇧🇿', 'North America'),
('CU', 'Cuba', '🇨🇺', 'North America'),
('DM', 'Dominica', '🇩🇲', 'North America'),
('DO', 'Dominican Republic', '🇩🇴', 'North America'),
('SV', 'El Salvador', '🇸🇻', 'North America'),
('GD', 'Grenada', '🇬🇩', 'North America'),
('GT', 'Guatemala', '🇬🇹', 'North America'),
('HT', 'Haiti', '🇭🇹', 'North America'),
('HN', 'Honduras', '🇭🇳', 'North America'),
('JM', 'Jamaica', '🇯🇲', 'North America'),
('NI', 'Nicaragua', '🇳🇮', 'North America'),
('PA', 'Panama', '🇵🇦', 'North America'),
('KN', 'Saint Kitts and Nevis', '🇰🇳', 'North America'),
('LC', 'Saint Lucia', '🇱🇨', 'North America'),
('VC', 'Saint Vincent and the Grenadines', '🇻🇨', 'North America'),
('TT', 'Trinidad and Tobago', '🇹🇹', 'North America'),
-- South America
('BO', 'Bolivia', '🇧🇴', 'South America'),
('CL', 'Chile', '🇨🇱', 'South America'),
('EC', 'Ecuador', '🇪🇨', 'South America'),
('GY', 'Guyana', '🇬🇾', 'South America'),
('PY', 'Paraguay', '🇵🇾', 'South America'),
('PE', 'Peru', '🇵🇪', 'South America'),
('SR', 'Suriname', '🇸🇷', 'South America'),
('UY', 'Uruguay', '🇺🇾', 'South America'),
('VE', 'Venezuela', '🇻🇪', 'South America'),
-- Oceania
('FJ', 'Fiji', '🇫🇯', 'Oceania'),
('KI', 'Kiribati', '🇰🇮', 'Oceania'),
('MH', 'Marshall Islands', '🇲🇭', 'Oceania'),
('FM', 'Micronesia', '🇫🇲', 'Oceania'),
('NR', 'Nauru', '🇳🇷', 'Oceania'),
('PW', 'Palau', '🇵🇼', 'Oceania'),
('PG', 'Papua New Guinea', '🇵🇬', 'Oceania'),
('WS', 'Samoa', '🇼🇸', 'Oceania'),
('SB', 'Solomon Islands', '🇸🇧', 'Oceania'),
('TO', 'Tonga', '🇹🇴', 'Oceania'),
('TV', 'Tuvalu', '🇹🇻', 'Oceania'),
('VU', 'Vanuatu', '🇻🇺', 'Oceania')
ON CONFLICT (code) DO NOTHING;